In [6]:
import pandas as pd
import numpy as np

In [7]:
#快速、灵活的多维大型数据集容器
#创建ndarray数组的四种方式
#方法一、直接将列表转换为ndarray类型4
array1 = np.array([12,23,43,35,54,56])

In [8]:
array1

array([12, 23, 43, 35, 54, 56])

In [9]:
#方法二
array2 = np.arange(1, 100, 2)

In [10]:
array2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [11]:
# 方法三、用linspace方法创建等差数列
array3 = np.linspace(1, 10, 9)

In [12]:
array3

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [14]:
# 方法四、使用随机数模块来创建
array4 = np.random.randint(1, 100, 6)

In [15]:
array4

array([40, 48, 62, 65, 68, 88])

In [43]:
# 创建二维
array5 = np.random.randint(1, 100, (5, 5))

In [44]:
array5

array([[91, 97, 34, 43,  2],
       [89, 52, 60,  5, 74],
       [31,  1, 55, 84, 97],
       [10, 24, 13, 23, 56],
       [48, 59, 91, 52, 69]])

In [19]:
#填充数组
#全一素组
array6 = np.ones((4, 4))

In [20]:
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#全零数组
array7 = np.zeros((4, 4))

In [22]:
array7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
#全六数组
array8 = np.full((4, 4), 6)

In [24]:
array8

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [25]:
#单位矩阵
array9 = np.eye(5)

In [26]:
array9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#查看数组信息
#数组的数据类型
array5.dtype

dtype('int32')

In [28]:
#数组的元素个数
array5.size

9

In [29]:
array5

array([[97,  6, 53],
       [30, 53, 75],
       [75,  5, 82]])

In [30]:
#数组的形状
array6.shape

(4, 4)

In [31]:
#数组的维度
array1.ndim

1

In [32]:
array6.ndim

2

In [33]:
#数组的排序、形状调整
array1.sort()

In [34]:
array1

array([12, 23, 35, 43, 54, 56])

In [35]:
#进行形状调整
array6.reshape(2, 8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
#描述性统计信息
array5.mean(axis=1)

array([53.4, 56. , 53.6, 25.2, 63.8])

In [46]:
array5

array([[91, 97, 34, 43,  2],
       [89, 52, 60,  5, 74],
       [31,  1, 55, 84, 97],
       [10, 24, 13, 23, 56],
       [48, 59, 91, 52, 69]])

In [47]:
# 求标准差
array5.std()

30.603267799370705

In [48]:
#求方差
array5.var()

936.56

In [50]:
#二维数组的切片
array5[1:4, 1:3]

array([[52, 60],
       [ 1, 55],
       [24, 13]])

In [51]:
array5[1:4, 2:]

array([[60,  5, 74],
       [55, 84, 97],
       [13, 23, 56]])

In [55]:
#数组的索引
#ndarray花式索引
array1[[0, 2, 4]]

array([12, 35, 54])

In [54]:
array1

array([12, 23, 35, 43, 54, 56])

In [57]:
#布尔索引
#大于40的数据
#用不存布尔值的数组充当索引（输出所有True对应的元素，不选Flase对应的元素）
array1[array1 > 40]

array([43, 54, 56])

In [64]:
#使用布尔索引输出所有的偶数
array1[array1 % 2 == 0]

array([12, 54, 56])

In [67]:
#数组的运算
array5

array([[91, 97, 34, 43,  2],
       [89, 52, 60,  5, 74],
       [31,  1, 55, 84, 97],
       [10, 24, 13, 23, 56],
       [48, 59, 91, 52, 69]])

In [68]:
array 5 + 2

array([[93, 99, 36, 45,  4],
       [91, 54, 62,  7, 76],
       [33,  3, 57, 86, 99],
       [12, 26, 15, 25, 58],
       [50, 61, 93, 54, 71]])

In [69]:
array5 ** 2

array([[8281, 9409, 1156, 1849,    4],
       [7921, 2704, 3600,   25, 5476],
       [ 961,    1, 3025, 7056, 9409],
       [ 100,  576,  169,  529, 3136],
       [2304, 3481, 8281, 2704, 4761]], dtype=int32)

In [70]:
#矩阵乘法
#前提：a矩阵的列数 = b矩阵的行数
arr1 = np.random.randint(1, 12, (2, 3))
arr2 = np.random.randint(1, 12, (3, 2))

In [71]:
arr1 @ arr2

array([[117,  96],
       [ 91,  77]])